:bug: restrict api call to /civic/suupport/users to only civicLiker2.0
likecoin/likecoin-button pull request #326
Opened 2021-02-23 09:27 UTC by shellyYG

fix redundant api calls on non-2.0 users

2021-02-23 09:45 UTC, nwingt requested changes

2021-02-23 09:45 UTC, nwingt commented on src/mixins/embed.js
> +                    }).catch(() => { });
```suggestion
                    }).catch(() => {});
```

2021-02-23 09:50 UTC, nwingt commented
For Gitmoji, I think ⚡️(Improve performance) is more precise than 🐛 (bug)

2021-02-24 10:52 UTC, williamchong requested changes

2021-02-24 10:52 UTC, williamchong commented on src/mixins/embed.js
> +              this.civicLikerVersion = civicLikerVersion;
Should first defined `civicLikerVersion` in `data()` before using it as `this.civicLikerVersion`

2021-02-24 11:48 UTC, williamchong approved these changes

2021-02-24 11:48 UTC, merged