🥅 Add alternative NFT related routes
likecoin/likecoin-button pull request #418
Opened 2022-09-02 10:48 UTC by nwingt

- `/in/nft/(:classId|:iscnId)`
- Redirect `/:iscnId` to `/in/like/iscn`
- Redirect `/:classId` to `/in/nft/:classId`

2022-09-02 11:08 UTC, williamchong commented
we also need to modify the oembed regex before this change deploy

2022-09-02 11:09 UTC, williamchong approved these changes

2022-09-02 11:09 UTC, williamchong commented on src/util/nft.js
> +export const checkIsValidNFTClassId = value => value.startsWith('likenft1');
We do have some regex we can use, but I guess these would do

2022-09-02 15:00 UTC, nwingt commented
> we also need to modify [the oembed regex](https://github.com/likecoin/likecoin-api-public/pull/341) before this change deploy

You mean adding `/in/nft/(:classId|:iscnId)`?

https://github.com/likecoin/likecoin-api-public/blob/57d443de8f250cec3911dcad5f67ea891c31ef58/src/routes/oembed/index.js#L80-L90

https://github.com/likecoin/likecoin-api-public/blob/57d443de8f250cec3911dcad5f67ea891c31ef58/src/routes/oembed/index.js#L130

2022-09-02 16:05 UTC, nwingt commented
Case 2 not working due to issue on Firebase Function

2022-09-03 08:14 UTC, williamchong commented
> > we also need to modify [the oembed regex](https://github.com/likecoin/likecoin-api-public/pull/341) before this change deploy
> 
> You mean adding `/in/nft/(:classId|:iscnId)`?
> 
> https://github.com/likecoin/likecoin-api-public/blob/57d443de8f250cec3911dcad5f67ea891c31ef58/src/routes/oembed/index.js#L80-L90
> 
> https://github.com/likecoin/likecoin-api-public/blob/57d443de8f250cec3911dcad5f67ea891c31ef58/src/routes/oembed/index.js#L130

i mean the /in/like regex in api is actually due to hardcode redirect, in which this PR will fix
so we should change the oembed api regex to use the new redirected path for iscn and nft, instead of/in/like

2022-09-03 14:00 UTC, nwingt commented
The ISCN ID or the NFT Class ID is in the qs of the updated redirect path, not in the path, so it should be working without changing the API RegEx?

2022-09-06 17:50 UTC, williamchong requested changes
Do we also want to handle unencoded iscn id via error page?
Smilar to https://github.com/likecoin/liker-land/pull/527

2022-09-06 17:50 UTC, williamchong commented on src/pages/in/nft/_id.vue
> +      error({ statusCode: 400, message: 'INVALID_NFT_IDENTIFIER' });
we can actually do [optional params in route](https://nuxtjs.org/docs/features/file-system-routing/#dynamic-routes) to merge this file with `index?

2022-09-06 17:50 UTC, williamchong commented on src/pages/iscn/_id.vue
> +};
we can actually do [optional params in route](https://nuxtjs.org/docs/features/file-system-routing/#dynamic-routes) to merge this file with `index?

2022-09-06 17:50 UTC, williamchong commented on src/pages/nft/_id.vue
> +      redirect({ name: 'in-nft', query: { class_id: id, ...query } });
we can actually do [optional params in route](https://nuxtjs.org/docs/features/file-system-routing/#dynamic-routes) to merge this file with `index?

2022-09-13 16:53 UTC, williamchong approved these changes

2022-09-13 16:56 UTC, merged